"""crm core tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-11 14:39:16.191924

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=512), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('territory', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('division', sa.String(length=128), nullable=True),
    sa.Column('num_employees', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('referred_by', sa.String(length=128), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('parent_company_id', sa.UUID(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('act_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('act_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_db', sa.String(length=20), nullable=False),
    sa.Column('source_act_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'source_act_id', name='uq_companies_source')
    )
    op.create_index(op.f('ix_companies_source_db'), 'companies', ['source_db'], unique=False)
    op.create_table('groups',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('hier_level', sa.Integer(), nullable=True),
    sa.Column('hier_path', sa.String(length=556), nullable=True),
    sa.Column('parent_group_id', sa.UUID(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_db', sa.String(length=20), nullable=False),
    sa.Column('source_act_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'source_act_id', name='uq_groups_source')
    )
    op.create_index(op.f('ix_groups_source_db'), 'groups', ['source_db'], unique=False)
    op.create_table('history_entries',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('history_type', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_db', sa.String(length=20), nullable=False),
    sa.Column('source_act_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint("entity_type IN ('contact', 'company')", name='ck_history_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'source_act_id', name='uq_history_entries_source')
    )
    op.create_index(op.f('ix_history_entries_entity_id'), 'history_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_history_entries_entity_type'), 'history_entries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_history_entries_history_type'), 'history_entries', ['history_type'], unique=False)
    op.create_index(op.f('ix_history_entries_occurred_at'), 'history_entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_history_entries_source_db'), 'history_entries', ['source_db'], unique=False)
    op.create_table('notes',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('act_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_db', sa.String(length=20), nullable=False),
    sa.Column('source_act_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint("entity_type IN ('contact', 'company')", name='ck_notes_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'source_act_id', name='uq_notes_source')
    )
    op.create_index(op.f('ix_notes_entity_id'), 'notes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notes_entity_type'), 'notes', ['entity_type'], unique=False)
    op.create_index(op.f('ix_notes_source_db'), 'notes', ['source_db'], unique=False)
    op.create_table('review_queue',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_review_queue_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_entity_id'), 'review_queue', ['entity_id'], unique=False)
    op.create_index(op.f('ix_review_queue_entity_type'), 'review_queue', ['entity_type'], unique=False)
    op.create_index(op.f('ix_review_queue_kind'), 'review_queue', ['kind'], unique=False)
    op.create_index(op.f('ix_review_queue_status'), 'review_queue', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('name_prefix', sa.String(length=64), nullable=True),
    sa.Column('name_suffix', sa.String(length=64), nullable=True),
    sa.Column('salutation', sa.String(length=64), nullable=True),
    sa.Column('job_title', sa.String(length=256), nullable=True),
    sa.Column('department', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=512), nullable=True),
    sa.Column('referred_by', sa.String(length=128), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('last_meet_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reach_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_letter_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('act_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('act_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_db', sa.String(length=20), nullable=False),
    sa.Column('source_act_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'source_act_id', name='uq_contacts_source')
    )
    op.create_index(op.f('ix_contacts_source_db'), 'contacts', ['source_db'], unique=False)
    op.create_table('activities',
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=128), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_timeless', sa.Boolean(), nullable=False),
    sa.Column('is_cleared', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_db', sa.String(length=20), nullable=False),
    sa.Column('source_act_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('contact_id IS NULL OR company_id IS NULL', name='ck_activities_one_owner'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'source_act_id', name='uq_activities_source')
    )
    op.create_index(op.f('ix_activities_source_db'), 'activities', ['source_db'], unique=False)
    op.create_table('addresses',
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('type_label', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('line1', sa.String(length=512), nullable=True),
    sa.Column('line2', sa.String(length=512), nullable=True),
    sa.Column('line3', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=512), nullable=True),
    sa.Column('state', sa.String(length=512), nullable=True),
    sa.Column('postal_code', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=512), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_db', sa.String(length=20), nullable=False),
    sa.Column('source_act_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('(contact_id IS NOT NULL) <> (company_id IS NOT NULL)', name='ck_addresses_one_owner'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'source_act_id', name='uq_addresses_source')
    )
    op.create_index(op.f('ix_addresses_source_db'), 'addresses', ['source_db'], unique=False)
    op.create_table('emails',
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('type_label', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_db', sa.String(length=20), nullable=False),
    sa.Column('source_act_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('(contact_id IS NOT NULL) <> (company_id IS NOT NULL)', name='ck_emails_one_owner'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'source_act_id', name='uq_emails_source')
    )
    op.create_index(op.f('ix_emails_address'), 'emails', ['address'], unique=False)
    op.create_index(op.f('ix_emails_source_db'), 'emails', ['source_db'], unique=False)
    op.create_table('group_memberships',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'contact_id', name='uq_group_memberships')
    )
    op.create_index(op.f('ix_group_memberships_contact_id'), 'group_memberships', ['contact_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=26), nullable=True),
    sa.Column('stage_name', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('competitor', sa.String(length=256), nullable=True),
    sa.Column('close_reason', sa.String(length=256), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=True),
    sa.Column('probability_pct', sa.SmallInteger(), nullable=True),
    sa.Column('open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_db', sa.String(length=20), nullable=False),
    sa.Column('source_act_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'source_act_id', name='uq_opportunities_source')
    )
    op.create_index(op.f('ix_opportunities_source_db'), 'opportunities', ['source_db'], unique=False)
    op.create_table('phones',
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('type_label', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_db', sa.String(length=20), nullable=False),
    sa.Column('source_act_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('(contact_id IS NOT NULL) <> (company_id IS NOT NULL)', name='ck_phones_one_owner'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'source_act_id', name='uq_phones_source')
    )
    op.create_index(op.f('ix_phones_source_db'), 'phones', ['source_db'], unique=False)
    # ### end Alembic commands ###
    # note: this migration intentionally does NOT touch the pre-existing
    # `users` table - alembic's autogenerate flagged an unrelated
    # nullability quirk on users.created_at, left alone here since it's
    # out of scope for the CRM core tables this migration adds.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phones_source_db'), table_name='phones')
    op.drop_table('phones')
    op.drop_index(op.f('ix_opportunities_source_db'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_contact_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_emails_source_db'), table_name='emails')
    op.drop_index(op.f('ix_emails_address'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_addresses_source_db'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_activities_source_db'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_contacts_source_db'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_review_queue_status'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_kind'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_entity_type'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_entity_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_notes_source_db'), table_name='notes')
    op.drop_index(op.f('ix_notes_entity_type'), table_name='notes')
    op.drop_index(op.f('ix_notes_entity_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_history_entries_source_db'), table_name='history_entries')
    op.drop_index(op.f('ix_history_entries_occurred_at'), table_name='history_entries')
    op.drop_index(op.f('ix_history_entries_history_type'), table_name='history_entries')
    op.drop_index(op.f('ix_history_entries_entity_type'), table_name='history_entries')
    op.drop_index(op.f('ix_history_entries_entity_id'), table_name='history_entries')
    op.drop_table('history_entries')
    op.drop_index(op.f('ix_groups_source_db'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_companies_source_db'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
