import type {
  ContactListItem,
  ContactDetail,
  CompanyListItem,
  CompanyDetail,
  GroupListItem,
  GroupDetail,
  DashboardStats,
  Page,
} from "./types";

export const MOCK_CONTACTS: ContactDetail[] = [
  {
    id: "cnt_01h8x1",
    source_db: "onboard",
    source_act_id: "ACT-ONB-90214",
    first_name: "Eleanor",
    middle_name: "Ruth",
    last_name: "Vance",
    full_name: "Eleanor Vance",
    job_title: "Head of Inflight Retail & Hospitality",
    department: "Guest Experience & Procurement",
    category: "Airline Key Account",
    referred_by: "WTCE Hamburg 2023",
    birthdate: "1982-06-14",
    last_meet_date: "2024-05-18T10:30:00Z",
    last_reach_date: "2024-06-02T14:15:00Z",
    last_attempt_date: "2024-05-30T09:00:00Z",
    last_letter_date: "2024-04-12T16:00:00Z",
    custom_fields: {
      "Issue 84 Feature Status": "Interview Confirmed (Lead Story)",
      "Print Copies Requested": 120,
      "Dietary & Sustainable Sourcing": "High Priority",
      "Preferred Title": "Onboard Hospitality",
      "Annual Ad Budget Tier": "Tier 1 Platinum (>£45k)",
    },
    company: {
      id: "cmp_01h8x1",
      name: "British Airways",
      source_db: "onboard",
      industry: "Aviation & Airline Catering",
      category: "Tier 1 Airline",
    },
    addresses: [
      {
        id: "addr_1",
        type_label: "Waterside HQ",
        line1: "Waterside, Speedbird Way",
        line2: "PO Box 365",
        line3: null,
        city: "Harmondsworth",
        state: "Middlesex",
        postal_code: "UB7 0GB",
        country: "United Kingdom",
      },
    ],
    phones: [
      { id: "ph_1", type_label: "Direct Line", number: "+44 (0)20 8738 5140" },
      { id: "ph_2", type_label: "Mobile", number: "+44 (0)7710 492815" },
    ],
    emails: [
      { id: "em_1", type_label: "Work Direct", address: "eleanor.vance@ba.com" },
      { id: "em_2", type_label: "Executive PA", address: "pa.hospitality@ba.com" },
    ],
    groups: [
      { id: "grp_1", name: "Onboard Hospitality Award Judges 2024" },
      { id: "grp_2", name: "Inflight Buyers - Tier 1 Europe" },
      { id: "grp_3", name: "Issue 84 Confirmed Advertisers" },
    ],
    notes: [
      {
        id: "note_101",
        note_type: "Editorial Meeting",
        body: "Met with Eleanor and Chef Nicholas at Waterside. Confirmed BA will headline Issue 84 with a 4-page spread on their new Club World dining rollout. Eleanor confirmed they want 120 extra print copies dispatched to Heathrow T5 lounge directors.",
        act_created_at: "2024-05-18T11:45:00Z",
      },
      {
        id: "note_102",
        note_type: "Advertising Renewal",
        body: "Agreed on full-page outside back cover insertion for the Autumn Annual Buyer's Guide. Rate agreed at £4,200 with standard agency commission terms. Invoicing via Xero once artwork approved.",
        act_created_at: "2024-04-20T15:20:00Z",
      },
      {
        id: "note_103",
        note_type: "Phone Catch-up",
        body: "Quick catch-up regarding OOO successor while Eleanor was on leave in April. Assistant confirmed all catering procurement requests run through her direct desk.",
        act_created_at: "2024-03-11T09:15:00Z",
      },
    ],
    history: [
      {
        id: "hist_1",
        history_type: "Call Reach",
        subject: "Discussed Issue 84 artwork deadlines & high-res image assets",
        occurred_at: "2024-06-02T14:15:00Z",
      },
      {
        id: "hist_2",
        history_type: "Meeting - In Person",
        subject: "Waterside Executive Dining Tasting Session",
        occurred_at: "2024-05-18T10:30:00Z",
      },
      {
        id: "hist_3",
        history_type: "Proposal Sent",
        subject: "Media Kit & Rate Card 2024/25 - Onboard Hospitality Digital Hub",
        occurred_at: "2024-04-12T16:00:00Z",
      },
    ],
  },
  {
    id: "cnt_01h8x2",
    source_db: "onboard",
    source_act_id: "ACT-ONB-90422",
    first_name: "Marcus",
    middle_name: null,
    last_name: "Thorne",
    full_name: "Marcus Thorne",
    job_title: "Commercial Director",
    department: "Advertising & Partnerships",
    category: "Airline Catering Supplier",
    referred_by: "Direct Inbound",
    birthdate: "1978-11-29",
    last_meet_date: "2024-04-09T14:00:00Z",
    last_reach_date: "2024-05-22T11:00:00Z",
    last_attempt_date: "2024-05-20T16:30:00Z",
    last_letter_date: null,
    custom_fields: {
      "Preferred Title": "Onboard Hospitality",
      "Expo Participation": "WTCE Hamburg Platinum Sponsor",
      "Digital Newsletter Banner": "Active (Monthly)",
    },
    company: {
      id: "cmp_01h8x2",
      name: "Gate Gourmet & Gategroup",
      source_db: "onboard",
      industry: "Catering & Airline Provisioning",
      category: "Global Caterer",
    },
    addresses: [
      {
        id: "addr_2",
        type_label: "Global HQ",
        line1: "Sägereistrasse 20",
        line2: null,
        line3: null,
        city: "Glattbrugg",
        state: "Zurich",
        postal_code: "8152",
        country: "Switzerland",
      },
    ],
    phones: [
      { id: "ph_3", type_label: "Direct Line", number: "+41 44 532 1000" },
      { id: "ph_4", type_label: "Mobile", number: "+41 79 401 2288" },
    ],
    emails: [
      { id: "em_3", type_label: "Work Direct", address: "mthorne@gategroup.com" },
    ],
    groups: [
      { id: "grp_2", name: "Inflight Buyers - Tier 1 Europe" },
      { id: "grp_3", name: "Issue 84 Confirmed Advertisers" },
    ],
    notes: [
      {
        id: "note_104",
        note_type: "Contract Discussion",
        body: "Marcus booked 6-issue insertion schedule covering all 2024/2025 print issues of Onboard Hospitality plus digital web banners. Wants editorial coverage on their new plant-based culinology hub in Frankfurt.",
        act_created_at: "2024-04-09T15:30:00Z",
      },
    ],
    history: [
      {
        id: "hist_4",
        history_type: "Call Reach",
        subject: "Confirmed advert dimensions for digital edition hyperlink embed",
        occurred_at: "2024-05-22T11:00:00Z",
      },
      {
        id: "hist_5",
        history_type: "Contract Signed",
        subject: "Annual Advertising Partnership Agreement 2024/25",
        occurred_at: "2024-04-10T17:00:00Z",
      },
    ],
  },
  {
    id: "cnt_01h8x3",
    source_db: "sellingtravel",
    source_act_id: "ACT-ST-44102",
    first_name: "Clara",
    middle_name: "Jane",
    last_name: "Sterling",
    full_name: "Clara Sterling",
    job_title: "Head of UK & European Trade Marketing",
    department: "International Tourism Promotion",
    category: "Tourist Board",
    referred_by: "WTM London",
    birthdate: "1986-03-22",
    last_meet_date: "2024-05-02T13:00:00Z",
    last_reach_date: "2024-06-08T15:45:00Z",
    last_attempt_date: null,
    last_letter_date: "2024-05-15T12:00:00Z",
    custom_fields: {
      "Preferred Title": "Selling Travel",
      "Focus Regions": "California, Pacific Northwest, US Roadtrips",
      "Webinar Co-host": "Scheduled for July 2024",
    },
    company: {
      id: "cmp_01h8x3",
      name: "Visit California UK",
      source_db: "sellingtravel",
      industry: "Destination Marketing & Tourism",
      category: "DMO / Tourism Board",
    },
    addresses: [
      {
        id: "addr_3",
        type_label: "London Bureau",
        line1: "56 Conduit Street",
        line2: "Mayfair",
        line3: null,
        city: "London",
        state: "Greater London",
        postal_code: "W1S 2YZ",
        country: "United Kingdom",
      },
    ],
    phones: [
      { id: "ph_5", type_label: "Office", number: "+44 (0)20 7257 6180" },
    ],
    emails: [
      { id: "em_4", type_label: "Primary Email", address: "csterling@visitcalifornia.co.uk" },
    ],
    groups: [
      { id: "grp_4", name: "Selling Travel Agent Training Partners" },
      { id: "grp_5", name: "North America Destination Specialists" },
    ],
    notes: [
      {
        id: "note_105",
        note_type: "Travel Trade Campaign",
        body: "Clara is keen to run a 16-page standalone supplement inside Selling Travel focusing on hidden coastal drives and eco-wineries. Budget approved via their Sacramento headquarters.",
        act_created_at: "2024-05-02T14:30:00Z",
      },
    ],
    history: [
      {
        id: "hist_6",
        history_type: "Call Reach",
        subject: "Finalized distribution list for UK travel agents & travel counsellors",
        occurred_at: "2024-06-08T15:45:00Z",
      },
    ],
  },
  {
    id: "cnt_01h8x4",
    source_db: "sellingtravel",
    source_act_id: "ACT-ST-44189",
    first_name: "Tariq",
    middle_name: null,
    last_name: "Al-Mansoor",
    full_name: "Tariq Al-Mansoor",
    job_title: "Senior Trade Relations Manager - Europe",
    department: "Commercial Sales",
    category: "Aviation & Network Carrier",
    referred_by: "Direct Corporate",
    birthdate: "1980-09-05",
    last_meet_date: "2024-05-12T16:00:00Z",
    last_reach_date: "2024-05-28T10:00:00Z",
    last_attempt_date: null,
    last_letter_date: null,
    custom_fields: {
      "Preferred Title": "Selling Travel",
      "Featured Hub": "Doha Hamad International",
    },
    company: {
      id: "cmp_01h8x4",
      name: "Qatar Airways",
      source_db: "sellingtravel",
      industry: "Aviation & Global Carrier",
      category: "5-Star Global Carrier",
    },
    addresses: [
      {
        id: "addr_4",
        type_label: "Regional Office",
        line1: "10-12 Russell Square",
        line2: "Bloomsbury",
        line3: null,
        city: "London",
        state: "Greater London",
        postal_code: "WC1B 5LF",
        country: "United Kingdom",
      },
    ],
    phones: [
      { id: "ph_6", type_label: "Direct Line", number: "+44 (0)20 7630 1900" },
    ],
    emails: [
      { id: "em_5", type_label: "Trade Email", address: "talmansoor@qatarairways.com.qa" },
    ],
    groups: [
      { id: "grp_4", name: "Selling Travel Agent Training Partners" },
    ],
    notes: [
      {
        id: "note_106",
        note_type: "Campaign Brief",
        body: "Discussed double-spread inside front cover for Selling Travel Gulf & Indian Ocean Special. Promoting new A350 suite configurations to high-end travel designers.",
        act_created_at: "2024-05-12T17:15:00Z",
      },
    ],
    history: [
      {
        id: "hist_7",
        history_type: "Call Reach",
        subject: "Trade incentives campaign review for UK independent agents",
        occurred_at: "2024-05-28T10:00:00Z",
      },
    ],
  },
  {
    id: "cnt_01h8x5",
    source_db: "prospects",
    source_act_id: "ACT-PRO-10022",
    first_name: "Sophia",
    middle_name: null,
    last_name: "Lindqvist",
    full_name: "Sophia Lindqvist",
    job_title: "Head of Sustainable Procurement",
    department: "Cabin Experience",
    category: "Prospect - Nordic Airline",
    referred_by: "Automated LinkedIn Enrichment",
    birthdate: "1988-02-18",
    last_meet_date: null,
    last_reach_date: "2024-06-11T09:30:00Z",
    last_attempt_date: "2024-06-10T14:00:00Z",
    last_letter_date: null,
    custom_fields: {
      "Enrichment Status": "Verified via Graph/LinkedIn",
      "Departure Replaced": "Replaced Anders Holst (retired April 2024)",
      "Target Title": "Onboard Hospitality",
    },
    company: {
      id: "cmp_01h8x5",
      name: "SAS Scandinavian Airlines",
      source_db: "prospects",
      industry: "Aviation & Passenger Transport",
      category: "Nordic Flag Carrier",
    },
    addresses: [
      {
        id: "addr_5",
        type_label: "Headquarters",
        line1: "Frösundaviks allé 1",
        line2: null,
        line3: null,
        city: "Solna",
        state: "Stockholm",
        postal_code: "195 87",
        country: "Sweden",
      },
    ],
    phones: [
      { id: "ph_7", type_label: "Direct Line", number: "+46 8 797 0000" },
    ],
    emails: [
      { id: "em_6", type_label: "Primary Email", address: "sophia.lindqvist@flysas.com" },
    ],
    groups: [
      { id: "grp_6", name: "High-Priority Prospects - Sustainable Inflight" },
    ],
    notes: [
      {
        id: "note_107",
        note_type: "AI Successor Detection",
        body: "Signal from CS-003: Detected Sophia taking over sustainable cabin procurement following Anders Holst departure. Verified active role via airline directory.",
        act_created_at: "2024-06-10T08:00:00Z",
      },
    ],
    history: [
      {
        id: "hist_8",
        history_type: "Call Reach",
        subject: "Introductory pitch regarding Onboard Hospitality Sustainability Guide",
        occurred_at: "2024-06-11T09:30:00Z",
      },
    ],
  },
];

export const MOCK_COMPANIES: CompanyDetail[] = [
  {
    id: "cmp_01h8x1",
    source_db: "onboard",
    source_act_id: "ACT-CMP-4011",
    name: "British Airways",
    description: "Flag carrier airline of the United Kingdom, operating a global network of passenger flights and premium cabin hospitality services.",
    industry: "Aviation & Airline Catering",
    category: "Tier 1 Airline",
    territory: "United Kingdom & Global",
    region: "Europe",
    website: "https://www.britishairways.com",
    num_employees: 40000,
    custom_fields: {
      "Fleet Size": "280+ Aircraft",
      "Catering Hubs": "London Heathrow (LHR), London Gatwick (LGW)",
      "Lead Publisher Rep": "Emma Richardson",
    },
    addresses: [
      {
        id: "caddr_1",
        type_label: "Corporate HQ",
        line1: "Waterside, Speedbird Way",
        line2: "PO Box 365",
        line3: null,
        city: "Harmondsworth",
        state: "Middlesex",
        postal_code: "UB7 0GB",
        country: "United Kingdom",
      },
    ],
    phones: [
      { id: "cph_1", type_label: "Main Switchboard", number: "+44 (0)20 8738 5000" },
    ],
    emails: [
      { id: "cem_1", type_label: "Corporate Relations", address: "corporate.hospitality@ba.com" },
    ],
    contacts: [
      {
        id: "cnt_01h8x1",
        source_db: "onboard",
        full_name: "Eleanor Vance",
        first_name: "Eleanor",
        last_name: "Vance",
        job_title: "Head of Inflight Retail & Hospitality",
        company_id: "cmp_01h8x1",
        company_name: "British Airways",
        primary_email: "eleanor.vance@ba.com",
      },
      {
        id: "cnt_01h8x6",
        source_db: "onboard",
        full_name: "Nicholas Sterling",
        first_name: "Nicholas",
        last_name: "Sterling",
        job_title: "Executive Development Chef - First & Club",
        company_id: "cmp_01h8x1",
        company_name: "British Airways",
        primary_email: "nicholas.sterling@ba.com",
      },
    ],
    notes: [
      {
        id: "cnote_1",
        note_type: "Account Review",
        body: "Annual account review with BA executive media team. They committed to maintaining continuous print insertion in Onboard Hospitality for all 2024 issues.",
        act_created_at: "2024-03-25T14:00:00Z",
      },
    ],
  },
  {
    id: "cmp_01h8x2",
    source_db: "onboard",
    source_act_id: "ACT-CMP-4012",
    name: "Gate Gourmet & Gategroup",
    description: "The world's largest provider of airline catering and hospitality provisioning, serving over 700 million passengers annually across 200+ airports.",
    industry: "Catering & Airline Provisioning",
    category: "Global Caterer",
    territory: "Worldwide",
    region: "Global",
    website: "https://www.gategroup.com",
    num_employees: 43000,
    custom_fields: {
      "Global Kitchens": "200+ operating airport units",
      "Publisher Status": "Strategic Print & Expo Sponsor",
    },
    addresses: [
      {
        id: "caddr_2",
        type_label: "Headquarters",
        line1: "Sägereistrasse 20",
        line2: null,
        line3: null,
        city: "Glattbrugg",
        state: "Zurich",
        postal_code: "8152",
        country: "Switzerland",
      },
    ],
    phones: [
      { id: "cph_2", type_label: "Head Office", number: "+41 44 532 1000" },
    ],
    emails: [
      { id: "cem_2", type_label: "Global Comms", address: "communications@gategroup.com" },
    ],
    contacts: [
      {
        id: "cnt_01h8x2",
        source_db: "onboard",
        full_name: "Marcus Thorne",
        first_name: "Marcus",
        last_name: "Thorne",
        job_title: "Commercial Director",
        company_id: "cmp_01h8x2",
        company_name: "Gate Gourmet & Gategroup",
        primary_email: "mthorne@gategroup.com",
      },
    ],
    notes: [
      {
        id: "cnote_2",
        note_type: "Commercial Agreement",
        body: "Six-issue double-spread sponsorship contract finalised with Marcus Thorne.",
        act_created_at: "2024-04-10T11:00:00Z",
      },
    ],
  },
];

export const MOCK_GROUPS: GroupDetail[] = [
  {
    id: "grp_1",
    name: "Onboard Hospitality Award Judges 2024",
    description: "Industry panel reviewing annual submissions for food, service innovation, amenities, and cabin tech.",
    parent_group_id: null,
    members: [
      {
        id: "cnt_01h8x1",
        source_db: "onboard",
        full_name: "Eleanor Vance",
        first_name: "Eleanor",
        last_name: "Vance",
        job_title: "Head of Inflight Retail & Hospitality",
        company_id: "cmp_01h8x1",
        company_name: "British Airways",
        primary_email: "eleanor.vance@ba.com",
      },
    ],
  },
  {
    id: "grp_3",
    name: "Issue 84 Confirmed Advertisers",
    description: "Commercial clients with confirmed print/digital insertions in Onboard Hospitality Issue 84.",
    parent_group_id: null,
    members: [
      {
        id: "cnt_01h8x1",
        source_db: "onboard",
        full_name: "Eleanor Vance",
        first_name: "Eleanor",
        last_name: "Vance",
        job_title: "Head of Inflight Retail & Hospitality",
        company_id: "cmp_01h8x1",
        company_name: "British Airways",
        primary_email: "eleanor.vance@ba.com",
      },
      {
        id: "cnt_01h8x2",
        source_db: "onboard",
        full_name: "Marcus Thorne",
        first_name: "Marcus",
        last_name: "Thorne",
        job_title: "Commercial Director",
        company_id: "cmp_01h8x2",
        company_name: "Gate Gourmet & Gategroup",
        primary_email: "mthorne@gategroup.com",
      },
    ],
  },
  {
    id: "grp_4",
    name: "Selling Travel Agent Training Partners",
    description: "Tourist boards and airlines conducting reader masterclasses for UK high street and home-working travel agents.",
    parent_group_id: null,
    members: [
      {
        id: "cnt_01h8x3",
        source_db: "sellingtravel",
        full_name: "Clara Sterling",
        first_name: "Clara",
        last_name: "Sterling",
        job_title: "Head of UK & European Trade Marketing",
        company_id: "cmp_01h8x3",
        company_name: "Visit California UK",
        primary_email: "csterling@visitcalifornia.co.uk",
      },
      {
        id: "cnt_01h8x4",
        source_db: "sellingtravel",
        full_name: "Tariq Al-Mansoor",
        first_name: "Tariq",
        last_name: "Al-Mansoor",
        job_title: "Senior Trade Relations Manager - Europe",
        company_id: "cmp_01h8x4",
        company_name: "Qatar Airways",
        primary_email: "talmansoor@qatarairways.com.qa",
      },
    ],
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  total_contacts: 118420,
  total_companies: 14612,
  total_groups: 832,
  contacts_by_source: [
    { source_db: "onboard", count: 48210 },
    { source_db: "sellingtravel", count: 39180 },
    { source_db: "prospects", count: 31030 },
  ],
  companies_by_source: [
    { source_db: "onboard", count: 6240 },
    { source_db: "sellingtravel", count: 4850 },
    { source_db: "prospects", count: 3522 },
  ],
  recent_contacts: [
    {
      id: "cnt_01h8x5",
      full_name: "Sophia Lindqvist",
      first_name: "Sophia",
      last_name: "Lindqvist",
      job_title: "Head of Sustainable Procurement",
      company_id: "cmp_01h8x5",
      company_name: "SAS Scandinavian Airlines",
      created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    },
    {
      id: "cnt_01h8x1",
      full_name: "Eleanor Vance",
      first_name: "Eleanor",
      last_name: "Vance",
      job_title: "Head of Inflight Retail & Hospitality",
      company_id: "cmp_01h8x1",
      company_name: "British Airways",
      created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    },
    {
      id: "cnt_01h8x3",
      full_name: "Clara Sterling",
      first_name: "Clara",
      last_name: "Sterling",
      job_title: "Head of UK & European Trade Marketing",
      company_id: "cmp_01h8x3",
      company_name: "Visit California UK",
      created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    },
  ],
  recent_companies: [
    {
      id: "cmp_01h8x1",
      name: "British Airways",
      industry: "Aviation & Airline Catering",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    },
    {
      id: "cmp_01h8x2",
      name: "Gate Gourmet & Gategroup",
      industry: "Catering & Airline Provisioning",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    },
    {
      id: "cmp_01h8x3",
      name: "Visit California UK",
      industry: "Destination Marketing & Tourism",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
  ],
  top_companies: [
    {
      id: "cmp_01h8x1",
      name: "British Airways",
      industry: "Aviation & Airline Catering",
      contact_count: 38,
    },
    {
      id: "cmp_01h8x2",
      name: "Gate Gourmet & Gategroup",
      industry: "Catering & Airline Provisioning",
      contact_count: 24,
    },
    {
      id: "cmp_01h8x3",
      name: "Visit California UK",
      industry: "Destination Marketing & Tourism",
      contact_count: 14,
    },
  ],
};
