export type RequirementStage =
  | "overview"
  | "foundation"
  | "stage1"
  | "stage2"
  | "stage3"
  | "stage4";

export type Automation = {
  id: string;
  code: string | null;
  name: string;
  stage: RequirementStage;
  effort: string | null;
  whatItDoes: string;
  howItWorks: string[];
  systemsAndData: string[];
  requirements: string[];
  questionsForClient: string[];
  edgeCases: string[];
  dependsOn: string[];
};

export const automations: Automation[] = [
  // ---------- OVERVIEW ----------
  {
    id: "overview",
    code: null,
    name: "Project Overview",
    stage: "overview",
    effort: null,
    whatItDoes:
      "BMI Publishing's Sales & Data Brain is a set of 23 automations plus an AI chat assistant, organized into a Foundation and four stages, all built around Act! CRM as the system of record. Stage 1 cleans and maintains the contact database (bounce handling, departure/successor tracking, deduplication, business-card intake). Stage 2 turns every call, email, and proposal into structured CRM history and adds an AI chat that lets reps ask questions about their clients in plain English. Stage 3 is the daily engine: automatically drafted follow-ups, a ranked morning task queue, proposal and renewal drafting, and pitch generation — always as a draft a human approves before sending. Stage 4 gives leadership a live pipeline, revenue dashboard, delivery tracking, and a weekly written brief. Total scope is roughly 93–144 build-days before integration/testing/PM overhead, originally spec'd for n8n but being rebuilt here as a FastAPI + Next.js + Postgres application.",
    howItWorks: [],
    systemsAndData: [],
    requirements: [],
    questionsForClient: [],
    edgeCases: [],
    dependsOn: [],
  },

  // ---------- MASTER QUESTIONS ----------
  {
    id: "master-questions",
    code: null,
    name: "Master Questions (Confirm Before Quoting)",
    stage: "overview",
    effort: null,
    whatItDoes:
      "These are the ten items from the original spec's \"must confirm before quoting\" list — the answers that move build estimates the most and, in a few cases, change what's technically possible at all. Resolve these first, before detailed scoping on any individual automation, because several automations are blocked or reshaped entirely depending on the answers (e.g. Act! Pro vs Premium changes whether a Web API exists at all).",
    howItWorks: [],
    systemsAndData: [],
    requirements: [
      "Act! Premium Web API base URL, version, and an auth token/API key with read/write access to Contacts, Notes, History, Activities, Opportunities, Companies, and Groups",
      "Read-only SQL Server Express credentials as a fallback path for bulk/read-heavy queries, if available",
      "Email platform admin access: app registration (e.g. Microsoft Graph for O365/Exchange, or Google Workspace equivalent) with mailbox-level permissions for inbox-watch and draft-into-mailbox on every rep's mailbox that needs it",
      "Teams and/or Zoom API/webhook access for call transcripts, plus confirmation that transcription is already licensed",
      "Access to the Sales Order Register in whatever form it currently exists (shared Excel file location/permissions, or a database connection if it moves)",
      "A confirmed, compliant enrichment/LinkedIn-data provider account and API key (not scraping — ToS risk)",
      "Xero API access (OAuth app or API key) scoped to the correct organisation/tenant, read-only",
      "A chosen LLM provider with a signed DPA and no-training guarantee, given ~10k contacts + ~40k prospects of EU personal data will pass through it",
      "A decision and access details for where this gets hosted (BMI's own server vs a managed VPS) — already resolved for this build: Dokploy-managed",
      "Digital-edition platform access or API docs, to confirm whether stable per-advertiser page URLs exist",
    ],
    questionsForClient: [
      "What Act! edition are you running — Premium (Desktop or Web) or Pro? Pro has no Web API at all, which changes the entire integration approach. If Premium Desktop only, can the Web API (IIS component) be installed on your server?",
      "What version of Act! is this, and are there any known API rate limits we should design around? Is a read-only SQL Server Express connection available as a fallback for bulk reads?",
      "Which email platform do you use for sales — O365/Exchange, Google Workspace, or something else — and how many mailboxes need inbox-watch and draft-into-mailbox access?",
      "Do you use Microsoft Teams, Zoom, or both for sales calls? Is call transcription already licensed/enabled, or would we need to add a transcription service (which has its own cost and data-residency implications)?",
      "The Sales Order Register is described as a shared, overwrite-prone Excel file today — is that still accurate, and would you be open to it moving to a database or Google/Excel Online sheet with real access control? This affects four separate automations (proposal assembly, renewal outreach, pipeline, and the revenue dashboard).",
      "For finding successors/replacements when a contact leaves a company, what's an acceptable, compliant way to look up who replaced them — a licensed data-enrichment provider (e.g. one with a LinkedIn data partnership), or should this stay a manual-assist step for a human to complete? Direct scraping of LinkedIn is against their Terms of Service and is the riskiest dependency in the whole build.",
      "Do you use Xero for accounting, and can we get read-only API access to the correct organisation/tenant for revenue reporting?",
      "Where is BMI's contact and prospect data allowed to be processed — do you need an EU-region LLM provider with a signed Data Processing Agreement and a guarantee that your data isn't used for model training?",
      "Do you want this hosted on your own server, or are you comfortable with a Cybix-managed VPS? (Note: this build already runs on a Cybix-managed Dokploy instance.)",
      "What platform hosts your digital editions, and can it produce a stable, durable URL for a specific advertiser's placement in a specific past issue? This is needed to link renewal emails back to a client's actual prior ad.",
      "Roughly how many contacts, prospects, bounces per mailing, and calls/emails per day/week should we plan for? This drives AI token-cost estimates, infrastructure sizing, and several of the day estimates above.",
    ],
    edgeCases: [],
    dependsOn: [],
  },

  // ---------- RUNNING COSTS ----------
  {
    id: "running-costs",
    code: null,
    name: "Running Costs (Monthly Opex)",
    stage: "overview",
    effort: null,
    whatItDoes:
      "Separate from the one-off build cost, this system has ongoing monthly running costs that scale with usage. Several of these can't be sized precisely until we know real volumes (contacts, prospects, calls, emails, mailings) — this page turns each cost category into a concrete sizing question to ask the client.",
    howItWorks: [],
    systemsAndData: [
      "Hosting (app server + database) — fixed monthly cost, already running on a Cybix-managed VPS via Dokploy for this build",
      "LLM API usage — per-token, the main variable cost, scales with call/email/proposal volume",
      "Vector store — hosting cost for the RAG index behind the AI chat",
      "Call transcription — only if not already covered by existing Teams/Zoom licensing",
      "Email verification — per-address, used by hygiene and card-capture flows",
      "Data enrichment (LinkedIn→email / people-move) — per-lookup, used by successor-finding and dedupe",
      "Support & maintenance — optional ongoing retainer",
    ],
    requirements: [],
    questionsForClient: [
      "Roughly how many sales calls happen per week, and how long on average? This drives transcription volume and LLM token cost for call-note capture.",
      "Roughly how many outbound and inbound sales emails per day/week, across how many reps? This drives LLM cost for proposal logging, email summarising, and follow-up drafting.",
      "How many contacts are in Act! today (spec assumes ~10,000) and how many prospects in the wider database (spec assumes ~40,000)? This sizes the initial AI-chat backfill and ongoing dedupe/hygiene volume.",
      "How many bounces typically come back per mailing (spec assumes 200+), and how many mailings go out per month/title?",
      "Is call transcription already included in your Teams or Zoom licensing, or would this need to be added as a separate paid service?",
      "Do you want an ongoing support/maintenance retainer, or will an internal person own day-to-day operation once it's built?",
    ],
    edgeCases: [],
    dependsOn: [],
  },

  // ---------- FOUNDATION ----------
  {
    id: "foundation",
    code: null,
    name: "Foundation & Act! Integration",
    stage: "foundation",
    effort: "Shared · Est. 10–16 days",
    whatItDoes:
      "The shared plumbing every other automation is built on top of: the Act! integration layer, the shared AI/LLM access, the vector store for the chat assistant, email and call-transcript ingestion, connectors to the Sales Order Register and Xero, enrichment/verification providers, and the human-review UI and notification channel every drafting workflow needs. This is the highest-risk, build-first piece — if the Act! Web API doesn't work the way the spec assumes, every other estimate in the project moves.",
    howItWorks: [
      "Backend service authenticates to the Act! Web API and exposes reusable helpers for contact matching (by name/company/email pattern), writing notes/history stamped with date + source + salesperson, and logging every automated action back to Act! for auditability",
      "A shared LLM client and prompt library handles extraction, classification, summarising, and drafting across all automations, so prompt behaviour and model choice are consistent and centrally managed",
      "A vector store is populated from Act! notes/history/proposals and re-indexed whenever new data is written, powering the AI chat's retrieval",
      "Email accounts are connected per-mailbox for inbox-watching (bounces, inbound mail, thread tracking) and for creating drafts directly in a rep's own mailbox — never sending on their behalf",
      "Call transcripts are pulled from Teams/Zoom as they become available and fed into the call-note and meeting-to-pitch automations",
      "The Sales Order Register and Xero are connected as read sources for proposals, renewals, pipeline, and revenue reporting",
      "A human-review UI provides the morning queue, draft approve/edit screens, chase lists, and exception queues that every automation with an AI-drafted output relies on",
      "A notification channel (Teams) posts \"ready to review\", exception, and alert messages",
    ],
    systemsAndData: [
      "Act! Web API (Contacts, Notes, History, Activities, Opportunities, Companies, Groups)",
      "SQL Server Express (read-only fallback)",
      "LLM API provider",
      "Vector store (e.g. Postgres pgvector or a dedicated vector DB)",
      "Email platform (O365/Exchange or equivalent), per-mailbox auth",
      "Teams/Zoom transcript source",
      "Sales Order Register connector",
      "Xero connector",
      "Enrichment + email-verification provider",
      "Human-review UI (built as part of this app)",
      "Teams notification webhook",
    ],
    requirements: [
      "Act! edition confirmed as Premium (not Pro), with Web API installed/exposable and a valid auth token",
      "Act! version number and any known rate limits",
      "SQL Server Express read-only credentials, if available, as a fallback",
      "Per-mailbox email app registration with inbox-read and draft-creation permissions",
      "Teams/Zoom API or webhook access for transcripts",
      "SOR access details (file location + permissions, or DB connection string)",
      "Xero API credentials + org/tenant ID",
      "Enrichment provider account/API key",
      "LLM provider account with EU data-residency/DPA terms confirmed",
    ],
    questionsForClient: [
      "Can you confirm Act! is Premium edition (not Pro) and that the Web API component is already installed, or can be installed, on your server?",
      "What are the practical rate limits on the Act! Web API in your environment — has anyone hit them before with other integrations?",
      "Who is the right technical contact to provision API credentials for Act!, email, Teams/Zoom, Xero, and the SOR?",
    ],
    edgeCases: [],
    dependsOn: [],
  },

  // ---------- STAGE 1 ----------
  {
    id: "cs-001",
    code: "CS-001",
    name: "Bounce Classification & Processing",
    stage: "stage1",
    effort: "Medium · Est. 3–5 days",
    whatItDoes:
      "Collects bounce replies after every mailing, classifies each one (hard bounce, soft bounce, out-of-office, auto-reply noise, or unknown), and automatically actions hard bounces in Act! while routing recoverable signals (like an out-of-office reply naming a replacement) downstream to other automations.",
    howItWorks: [
      "A scheduled job polls the sending mailbox(es) every 15–30 minutes after a mailing, looking for unread messages matching bounce heuristics (DSN/subject patterns)",
      "The message is parsed for SMTP status code, failed-recipient address, and body text; a regex pre-filter separates clear 5xx (hard) from 4xx (soft) cases",
      "Ambiguous or text-only bounces are sent to the LLM for classification, returning a class, SMTP code, reason text, and confidence score",
      "Hard bounces trigger an Act! contact lookup by email and a write: the contact is flagged unsubscribed and a History note is stamped with source, date, and mailing ID — nothing is hard-deleted",
      "Soft bounces are logged to a counter that escalates after a configurable number of failures in a rolling window",
      "Out-of-office or referral replies are handed off to the departure/successor automation (CS-002)",
      "A per-mailing summary is posted to the team notification channel, with unclear cases sent to a human review queue",
    ],
    systemsAndData: [
      "Email inbox-watch (per sending mailbox)",
      "LLM API (classification)",
      "Act! Web API (Contacts lookup + write, History)",
      "Team notification channel",
      "Human-review queue",
    ],
    requirements: [
      "Confirmed email platform and access to the sending mailbox(es) used for title/salesperson mailings",
      "Act! Web API write access to Contacts (unsubscribe flag) and History",
    ],
    questionsForClient: [
      "Which mailbox(es) send each title's mailings, and can we get inbox-read access to them?",
      "How quickly after a mailing do you need bounces processed — is a 15–30 minute poll cadence acceptable, or do you need it faster?",
      "How many failed sends in what time window should count as a \"soft bounce escalation\" worth a human look (e.g. 3 fails in 30 days)?",
    ],
    edgeCases: [
      "Non-English MTA bounce text",
      "Bounce recipient differs from the original list address (relay/alias)",
      "Challenge-response auto-replies mis-read as a referral",
      "Catch-all domains that never hard-bounce",
      "The same contact bouncing across three different titles",
      "Act! email match failing due to formatting differences",
    ],
    dependsOn: [],
  },
  {
    id: "cs-002",
    code: "CS-002",
    name: "Out-of-Office Replacement Mining",
    stage: "stage1",
    effort: "Medium · Est. 3–5 days",
    whatItDoes:
      "Reads each out-of-office or auto-reply for a named alternate contact, successor, or return date, verifies that person against Act!, and writes the replacement with a compliance note — without ever mistaking a temporary absence for a permanent replacement.",
    howItWorks: [
      "Receives a handoff from CS-001 whenever a reply is classed as out-of-office or an auto-reply referral, along with the email body and originating contact",
      "The LLM extracts any alternate name/email/phone, whether they're a successor, a return date, or a general departmental address",
      "If a named alternate is found, Act! is fuzzy-matched on name + company to avoid creating a duplicate; if no match exists, a new contact is created under the same company",
      "The original contact is updated and a compliance note is written with the source (OOO reply + message ID) and date",
      "If the reply confirms departure with no named alternate, it's handed off to the departure/successor automation (CS-003)",
      "Anything ambiguous — especially a possible confusion between \"I'm away until X\" and \"I've left, contact Y\" — goes to a human review queue with the original reply attached",
    ],
    systemsAndData: [
      "LLM API (extraction)",
      "Act! Web API (Contacts search/create/update, Notes/History)",
      "Enrichment provider (optional email-pattern verification)",
      "Human-review queue",
    ],
    requirements: [
      "Act! Web API write access to Contacts and Notes",
    ],
    questionsForClient: [
      "If someone's out-of-office reply says they're returning within N days, should we skip creating a \"replacement\" entirely? What's a sensible grace-period number of days?",
    ],
    edgeCases: [
      "Temporary absence with a return date mistaken for a permanent replacement",
      "A PA or reception given as a generic alternate rather than a real successor",
      "The alternate already exists in Act! under a variant spelling",
      "Multiple names mentioned in one reply",
      "Alternate's email domain doesn't match (external PA)",
    ],
    dependsOn: ["cs-001"],
  },
  {
    id: "cs-003",
    code: "CS-003",
    name: "Departure Detection & Successor Finding",
    stage: "stage1",
    effort: "High · Est. 6–9 days",
    whatItDoes:
      "Detects that a contact has left their role from any of three signal types, finds and verifies their same-role successor, writes the successor across every record that person held (a company can hold 6+ separate records for one person across titles/lists), and falls back to a verified general company address if no successor can be confirmed.",
    howItWorks: [
      "Normalises three different signal sources into one shape: a \"no longer here\" hard bounce from CS-001, an out-of-office-without-alternate from CS-002, or a people-move alert from an enrichment/monitoring service",
      "Enumerates every Act! record the departed person holds under that company (a related-contacts fan-out query), since one person can appear on multiple lists/titles",
      "Runs enrichment/web research to find a same-role, same-company successor candidate",
      "An LLM verification step scores the candidate against the role and company and applies a confidence gate",
      "If confirmed, every sibling record is updated with the new person and a stamped note; if not, a verified general company address is substituted so circulation continues uninterrupted",
      "Anything unresolved goes to a human review queue with the full research bundle attached, plus a notification alert",
    ],
    systemsAndData: [
      "LLM API (research synthesis + verification)",
      "Enrichment provider (LinkedIn→email, people-move alerts)",
      "Act! Web API (company→contacts fan-out, multi-record update, Notes)",
      "Web fetch capability",
      "Human-review queue",
      "Team notification channel",
    ],
    requirements: [
      "A confirmed, GDPR-compliant enrichment/people-move data provider with an API key",
      "Act! Web API access sufficient to enumerate and bulk-update all sibling records under one company",
    ],
    questionsForClient: [
      "What confidence threshold should trigger an automatic write versus a human review — are you comfortable with any auto-writes here, or should every successor change be reviewed first given the risk of writing a wrong person into multiple records?",
      "If we can't verify a successor at all, what should the fallback general company address look like, and who verifies it's still current?",
    ],
    edgeCases: [
      "Wrong-person successor due to a common name",
      "A role split across two people",
      "Company restructure or closure",
      "Enrichment data is stale or GDPR-restricted",
      "Only some of the person's 6+ records are found (matching gaps)",
      "General address turns out to be unverifiable",
      "The same departure is reported by two different signals and needs to be processed only once (idempotency)",
    ],
    dependsOn: ["cs-001", "cs-002"],
  },
  {
    id: "cs-004",
    code: "CS-004",
    name: "Duplicate & Moved-Person Record Merging",
    stage: "stage1",
    effort: "High · Est. 6–9 days",
    whatItDoes:
      "Detects duplicate and similar-name records across reader lists and the ~40,000-record prospects database, confirms genuine moved-person cases (rather than two different people with the same name), merges old records into new ones with full history preserved, and runs a rolling retirement pass over stale records — nothing is ever deleted silently.",
    howItWorks: [
      "Event path: when a new registration or re-subscription arrives, Act! is searched for an exact email match, then a fuzzy name+company match, producing a candidate set",
      "Batch path: a scheduled job pulls a batch of records, groups them by a blocking key (surname or email domain), and runs pairwise similarity scoring",
      "An LLM adjudication step decides whether a candidate pair is the same person, and whether they appear to have moved companies",
      "A LinkedIn/enrichment check confirms genuine moved-person cases",
      "Confirmed moves are merged (new record survives, old is retired with history preserved) with a stamped note; silent re-subscription failures are flagged separately",
      "Batch runs produce a reviewable list of dead/stale/duplicate candidates for retirement — uncertain matches always go to a human queue, never auto-merged",
    ],
    systemsAndData: [
      "Act! Web API (search, merge/retire, Notes) or SQL Server read fallback for bulk scanning",
      "LLM API (match adjudication)",
      "Enrichment/LinkedIn provider (identity confirmation)",
      "Human-review queue",
      "Team notification channel",
    ],
    requirements: [
      "Act! Web API or SQL read access capable of scanning ~40,000 prospect records efficiently",
      "Enrichment provider access for moved-person confirmation",
    ],
    questionsForClient: [
      "What similarity threshold feels safe to you for auto-merging two records versus sending them to a human — given a false merge of two genuinely different people (e.g. father and son with the same name) is effectively irreversible?",
      "What's your policy on retiring stale/dead records — how old does a record need to be with no activity before it's a retirement candidate, and do you want retention or deletion for GDPR purposes?",
      "How often should the rolling dedupe pass run, and in what batch sizes are you comfortable reviewing?",
    ],
    edgeCases: [
      "False-merge of genuinely different people with the same name (namesake trap)",
      "Partial-match families (e.g. father/son with identical names)",
      "Act!'s merge API limitations may require a field-copy-then-retire pattern instead of a true merge",
      "40,000-record scan performance favors the SQL read path over the Web API",
      "GDPR considerations around retention vs deletion",
      "Re-subscriptions silently blocked at the email service provider end",
    ],
    dependsOn: [],
  },
  {
    id: "cs-005",
    code: "CS-005",
    name: "Returned Copy Processing",
    stage: "stage1",
    effort: "Low · Est. 1–2 days",
    whatItDoes:
      "Reads each returned print-copy label from an undeliverable mailing, matches it to its Act! record, and either corrects the address or retires the record with a reason — turning a manual post-room task into a quick review-and-confirm step.",
    howItWorks: [
      "An operator photographs or scans a batch of returned label images and uploads them via a form or email",
      "Each label image is read with OCR/vision to extract text, then parsed by the LLM into a structured address plus any customer/mailing reference",
      "Act! is searched for a matching contact by reference first, falling back to name + company + postcode",
      "If the company appears to have moved, the address is corrected and a History note added; if closed, the record is retired with a reason; if nothing matches, it goes to a review queue",
      "A per-title batch summary is posted for quick review",
    ],
    systemsAndData: [
      "OCR/vision service (label reading)",
      "LLM API (address parsing/adjudication)",
      "Act! Web API (Contacts match, address update, History)",
      "Human-review queue",
    ],
    requirements: [
      "An intake channel for uploading photographed labels (form or email)",
      "An OCR/vision provider account",
    ],
    questionsForClient: [
      "How do you want to submit returned-copy batches — a simple upload form, or by forwarding an email with photos attached?",
      "What's your standard taxonomy for retiring a record — e.g. \"moved\", \"closed\", \"unknown\" — or should we define one?",
    ],
    edgeCases: [
      "Poor OCR quality on skewed or marked labels",
      "Multiple contacts registered at one returned address",
      "No reference number on the label, requiring name/company match only",
      "Temporary vs permanent move ambiguity",
      "Retire-vs-correct ambiguity",
    ],
    dependsOn: [],
  },
  {
    id: "sales-001",
    code: "SALES-001",
    name: "Business Card Reading & Extraction",
    stage: "stage1",
    effort: "Low · Est. 2–3 days",
    whatItDoes:
      "Turns photographed trade-show business cards — including multiple cards in one photo — into structured contact records automatically, flagging anything unreadable rather than guessing.",
    howItWorks: [
      "A team member uploads card photos via a form or email after a show, along with the show name and date",
      "Vision detects and crops each individual card region out of a multi-card photo",
      "Each card is OCR/vision-extracted, then the LLM normalizes the fields into name, company, job title, email, phone, and address",
      "Low-confidence cards are flagged for a quick human correction rather than guessed",
      "The structured batch, stamped with the show name and date, is handed off to the dedupe/group-assignment step (SALES-002)",
    ],
    systemsAndData: [
      "Intake form or email",
      "OCR/vision model (card detection + reading)",
      "LLM API (field structuring)",
    ],
    requirements: [
      "An intake channel for card photo uploads",
      "An OCR/vision provider account",
    ],
    questionsForClient: [
      "How do reps currently submit trade-show cards after an event — would a simple upload form work, or do you prefer email intake?",
      "How many cards would a typical photo batch contain — should we design for single-card photos or multi-card shots as the norm?",
    ],
    edgeCases: [
      "Multiple cards overlapping in one photo",
      "Double-sided cards (logo on the reverse)",
      "Non-Latin scripts",
      "QR-only \"digital\" cards with no printed text",
      "Handwriting on the card",
      "Glare or rotation",
      "Multiple emails/phone numbers on one card",
    ],
    dependsOn: [],
  },
  {
    id: "sales-002",
    code: "SALES-002",
    name: "Card Contact Dedupe & Group Assignment",
    stage: "stage1",
    effort: "Low · Est. 1–2 days",
    whatItDoes:
      "Checks every card contact read by SALES-001 against Act!, suggests appropriate CRM groups for new contacts, surfaces changed details on existing ones, and writes the whole batch to Act! on a single confirmation.",
    howItWorks: [
      "Receives a structured batch of card contacts from SALES-001",
      "Each contact is matched against Act! by email, then by name + company as a fallback",
      "Existing contacts show a diff of what's changed; new contacts get an LLM-suggested set of groups based on Act!'s existing group taxonomy",
      "A single review list is built showing additions (with suggested groups) and updates (with changed fields) for a specialist to confirm or adjust",
      "On confirmation, new contacts and group memberships are written, existing contacts are updated, and every record gets a source-show + date stamp",
      "A summary of added/updated/skipped is posted for visibility",
    ],
    systemsAndData: [
      "Act! Web API (Contacts search, Groups read/assign, create/update, Notes)",
      "LLM API (group suggestion + change detection)",
      "Human-review UI",
    ],
    requirements: [
      "Act! Web API write access to Contacts and Groups",
      "A copy of the current Act! Groups taxonomy to train suggestions against",
    ],
    questionsForClient: [
      "Can you share your current Act! Groups taxonomy (company type, role, territory, etc.) so group suggestions are accurate from day one?",
      "For new contacts from a card scan, do you want them written to Act! automatically once reviewed, or should every single one require an explicit confirm click?",
    ],
    edgeCases: [
      "Same person at a different company — correctly treated as a new record, not a duplicate",
      "Company-name variants blocking an accurate match",
      "Generic info@ emails defeating email-pattern matching",
      "No taxonomy group fits a new contact",
      "Two new cards in the same batch that are duplicates of each other",
    ],
    dependsOn: ["sales-001"],
  },

  // ---------- STAGE 2 ----------
  {
    id: "sales-008",
    code: "SALES-008",
    name: "Call Note Capture to the CRM",
    stage: "stage2",
    effort: "Medium · Est. 4–6 days",
    whatItDoes:
      "Turns every finished Teams or Zoom sales call into a structured, tagged Act! note against the right contact, with zero manual typing — capturing products discussed, rates mentioned, budget signals, and objections.",
    howItWorks: [
      "Triggered by a call-ended/transcript-ready webhook from Teams or Zoom, with a scheduled fallback poll of the transcription store every 15 minutes",
      "Fetches the transcript and meeting metadata (organiser, participants, start/end time, title)",
      "Normalizes speaker turns, strips filler words, and chunks the transcript if it exceeds the model's context window",
      "Matches the call to an Act! contact/company by participant email, falling back to email-domain + fuzzy name match; low-confidence matches go to a human review queue rather than being guess-written",
      "The LLM extracts a structured summary: interest, products discussed, rates mentioned (verbatim), a budget signal with amount and window, timing signal, objections, and personal notes",
      "Writes one Act! note per call, stamped with date, source, and salesperson, and tags budget/timing signals so the follow-up engine can query them later",
      "A daily per-rep digest lists captured notes with a one-click correct/reject option",
    ],
    systemsAndData: [
      "Teams/Zoom transcription (licensing to confirm)",
      "LLM API (provider + GDPR/data-residency to confirm)",
      "Act! Web API (Contacts, Companies, Notes, Groups)",
      "SQL Server read fallback",
      "Team notification channel (digest)",
    ],
    requirements: [
      "Teams and/or Zoom transcription licensing and webhook/API access",
      "Act! Premium Web API write access to Notes",
      "A confirmed LLM provider with residency/DPA sign-off, since call content is personal data",
    ],
    questionsForClient: [
      "Is call transcription already enabled and licensed in your Teams/Zoom setup, or does this need to be turned on/added?",
      "What confidence threshold feels right for auto-writing a note versus holding it for review when the system isn't sure which contact a call belongs to?",
      "What time should the daily per-rep digest be delivered?",
    ],
    edgeCases: [
      "Multi-party calls — attribute to the primary external contact, log others separately",
      "No transcript or a silent call — skip and log, don't guess",
      "Ambiguous contact (shared domain, name absent) — always goes to review, never guess-written",
      "Act! API token expiry — refresh and retry with backoff",
      "Duplicate webhook delivery — idempotency key on call ID",
    ],
    dependsOn: [],
  },
  {
    id: "sales-009",
    code: "SALES-009",
    name: "Proposal Logging to the CRM",
    stage: "stage2",
    effort: "Medium · Est. 3–5 days",
    whatItDoes:
      "Detects every outbound proposal email and logs exactly what was quoted — products, prices, terms — against the client in Act!, creating the contact if they're new to the CRM.",
    howItWorks: [
      "Watches the sent-mail folder for outbound messages matching an agreed convention (e.g. subject/body starting with \"proposal\")",
      "Extracts the email body text; any PDF/DOCX attachment is run through OCR/vision to extract text",
      "The LLM parses out line items: product, quantity, unit price, and terms",
      "The recipient is matched in Act! by email; if not found, a new contact is created from the email signature with suggested groups",
      "A structured note recording the full quote is written, and an Act! Activity is created as a follow-up trigger for a later date",
      "Unreadable attachments or ambiguous parses go to a human review queue rather than being silently skipped",
    ],
    systemsAndData: [
      "Email integration (O365/Exchange to confirm), Sent Items access",
      "OCR/vision (scanned/PDF quotes)",
      "LLM API",
      "Act! Web API (Contacts, Companies, Groups, Notes, Activities)",
    ],
    requirements: [
      "Sent-folder access to every rep mailbox that sends proposals",
      "Act! Web API write access to Activities (for the follow-up trigger)",
      "An agreed convention for identifying a proposal email (subject line prefix or similar)",
    ],
    questionsForClient: [
      "How do reps currently signal that an email is a formal proposal — is there an existing subject-line convention, or should we agree one?",
      "How many days after a proposal is sent should the automatic follow-up be scheduled by default?",
      "For a brand-new contact discovered this way, should we create them in Act! automatically, or wait for a rep to confirm first?",
    ],
    edgeCases: [
      "Attachment is unreadable or encrypted — goes to review",
      "Proposal sent to an existing multi-contact company — attach to the addressed contact only",
      "False positives on the detection convention — handled with a confidence gate and rep confirmation for new-contact creates",
      "A revised/re-sent proposal appends a new note rather than overwriting the old one",
      "Multi-currency or discounted line items are captured as-is, not normalized",
    ],
    dependsOn: [],
  },
  {
    id: "sales-010",
    code: "SALES-010",
    name: "Email Exchange Summarising to the CRM",
    stage: "stage2",
    effort: "Medium · Est. 4–6 days",
    whatItDoes:
      "When a meaningful client email exchange goes quiet, writes a concise Act! note capturing what was discussed, offered, agreed, and at what rate — while completely ignoring routine back-and-forth pleasantries and confirmations.",
    howItWorks: [
      "Inbox-watch captures new client mail and records the thread plus a last-activity timestamp in a state store",
      "A scheduled sweep looks for threads that have gone idle for N configurable hours",
      "A noise filter (rules plus an LLM classifier) drops threads that are pure confirmations, pleasantries, or auto-replies before any summarising happens",
      "The full thread is assembled in order and summarised by the LLM into what was discussed, what package/rate was offered, and any agreed or promised next steps, with the rate captured verbatim",
      "The contact is matched by the external participant's email and a single Act! note is written, tagged with any budget/timing signals for the follow-up engine",
      "If the thread reopens after being summarised, a supplementary note is appended rather than duplicating the first one",
    ],
    systemsAndData: [
      "Email integration (platform to confirm)",
      "LLM API",
      "Act! Web API (Contacts, Companies, Notes, Groups)",
      "State store for thread tracking",
    ],
    requirements: [
      "Inbox-watch access to each rep's mailbox",
      "A state store to track thread idle-time",
    ],
    questionsForClient: [
      "How many hours of silence on a thread should count as \"the conversation is closed\" and ready to summarise?",
      "How aggressively should the noise filter drop routine threads — are you more concerned about missing a real conversation, or about clutter from pure \"thanks!\" replies?",
    ],
    edgeCases: [
      "Thread reopens after being summarised — append, don't duplicate",
      "Internal-only or mixed internal/external threads — summarise external-facing content only",
      "Very long threads exceeding the model's context window — handled with a map-reduce summarising approach",
      "CC'd third parties attributed to the primary contact",
      "An over-eager noise filter accidentally dropping a real exchange — the daily digest lets a rep flag misses",
    ],
    dependsOn: ["sales-008"],
  },
  {
    id: "sales-011",
    code: "SALES-011",
    name: "Inbound Contact Capture",
    stage: "stage2",
    effort: "Low · Est. 2–3 days",
    whatItDoes:
      "When mail arrives from someone not already in Act!, extracts their details from the signature and offers a rep a one-click add with suggested groups and an optional newsletter opt-in — no contact is ever created without a human clicking accept.",
    howItWorks: [
      "Inbox-watch runs across each sales mailbox",
      "The sender's email is checked against Act!; if already present, nothing happens",
      "A noise filter drops automated, marketing, no-reply, and list mail using header heuristics plus a classifier",
      "The LLM parses the email signature into structured contact fields",
      "A one-click suggestion card appears in the review UI showing the parsed details, suggested groups, and a newsletter toggle",
      "On accept, the contact is created in Act! with group memberships and a source stamp; on decline, nothing is written",
    ],
    systemsAndData: [
      "Email integration (platform to confirm)",
      "LLM/parsing for signature extraction",
      "Act! Web API (Contacts, Groups)",
      "Human-review UI",
    ],
    requirements: [
      "Inbox-watch access to each sales mailbox",
      "Act! Groups already defined to suggest against",
    ],
    questionsForClient: [
      "Should shared/role mailboxes (info@, sales@) be excluded entirely from this, since they rarely represent a real individual worth adding?",
      "What's the default answer for the newsletter opt-in toggle — on or off by default when a new contact is suggested?",
    ],
    edgeCases: [
      "Sender already in Act! under a different address — surfaces as a possible duplicate rather than creating a new record",
      "Sparse or missing signature — partial card, rep completes the rest",
      "Shared/role mailboxes suppressed or flagged low-confidence",
      "Marketing mail that slips the filter — rep simply dismisses the card",
    ],
    dependsOn: [],
  },
  {
    id: "ai-hub-chat",
    code: "AI Hub Chat",
    name: "AI Hub Chat — Plain-English CRM Interrogation",
    stage: "stage2",
    effort: "High · Est. 8–12 days",
    whatItDoes:
      "Lets a salesperson ask a chat assistant plain-English questions about a client — \"what did they last buy, what's their budget window, what was the last rate?\" — and get a grounded answer with a citation back to the source Act! record, scoped so a rep can only see what they're allowed to see.",
    howItWorks: [
      "Initial backfill paginates every Act! contact and its notes/history/activities/opportunities, chunking one record per note/history/opportunity/activity plus a rolled-up contact profile, so every citation maps to exactly one source record",
      "Each chunk is embedded and stored in a vector database with metadata: contact, company, record type, owner rep, date, and a deep-link back to Act!",
      "Every time SALES-008/009/010/011 write a new note or contact, the new record is embedded and upserted so the index never lags the CRM; a nightly full reconciliation catches manual edits made directly in Act!",
      "A user's query is resolved to identify a named client (with disambiguation if there's more than one match), then access-scoped by the querying rep's identity before any search happens",
      "Retrieval combines vector search with keyword search (needed for exact rates/dates that pure semantic search can miss), then re-ranks the top results",
      "The LLM answers only from the retrieved chunks, citing each source record — if there's no evidence, it says so explicitly rather than guessing",
    ],
    systemsAndData: [
      "Act! Web API + SQL read fallback for bulk export",
      "Embedding model + LLM API (provider + GDPR/residency to confirm)",
      "Vector store (self-hosted, e.g. pgvector)",
      "Teams bot framework or web chat surface",
      "SSO identity mapping to rep/team",
    ],
    requirements: [
      "A hosting decision and setup for the vector store",
      "LLM/embedding provider with confirmed residency/DPA terms",
      "A decision on the chat surface: Teams bot vs web app",
      "SSO identity mapping so a query can be scoped to the right rep/team",
    ],
    questionsForClient: [
      "Should reps be able to see other reps' client history through this chat, or must access be strictly scoped so a rep only sees their own clients? Are there any exceptions (e.g. managers see everyone)?",
      "Would you rather this live as a bot inside Microsoft Teams (using your existing Teams identity for access control), or as a standalone web app?",
      "Is there a house style or format you'd want answers to follow, or is a plain grounded answer with a citation sufficient?",
    ],
    edgeCases: [
      "Stale index vs a live Act! edit — handled with re-index-on-write plus nightly reconciliation",
      "Ambiguous client name — the assistant asks for disambiguation",
      "Empty or insufficient retrieval — explicit \"no record found\" rather than fabrication",
      "Access-scope leak — must be enforced server-side and tested, not just in the UI",
      "Exact-figure queries (e.g. \"what was the last rate\") missed by pure vector search — handled with hybrid keyword retrieval",
      "Changing the embedding model requires a full re-embed migration",
    ],
    dependsOn: ["sales-008", "sales-009", "sales-010", "sales-011"],
  },

  // ---------- STAGE 3 ----------
  {
    id: "sales-012",
    code: "SALES-012",
    name: "Budget-Window & Renewal Triggers",
    stage: "stage3",
    effort: "Medium · Est. 4–6 days",
    whatItDoes:
      "Fires a context-assembled follow-up ahead of every budget window, promised call-back, or renewal date recorded in Act!, drafted and queued for the owning salesperson — so nothing falls through the cracks and no rep has to remember dates manually.",
    howItWorks: [
      "Runs hourly during business hours, scanning Act! for date-typed intents (budget-window month, renewal date, promised call-back) whose due date minus a lead window (default 14 days) has arrived and isn't already actioned",
      "For each trigger, fetches the contact, recent history, any open opportunity, previous bookings, and recent coverage into one context object",
      "Dedupes against already-queued triggers so the same thing doesn't get queued twice",
      "The LLM drafts a follow-up email in the owning rep's voice, referencing the earlier conversation, and it's written to the review-queue store with an urgency score and estimated value",
      "A parallel reply-watch process detects if the client already replied on that thread and stands the trigger down so it's never re-queued",
    ],
    systemsAndData: [
      "Act! Web API (Activities, Contacts, Notes, History, Opportunities)",
      "SQL read fallback for date sweeps",
      "LLM API (drafting)",
      "Human-review queue (shared with SALES-013)",
      "Email inbox-watch for reply detection",
    ],
    requirements: [
      "Voice profiles per salesperson so drafts sound like them, not a generic template",
      "Act! fields/tags for budget-window, renewal date, and promised call-back must be consistently populated (fed by SALES-008/010)",
    ],
    questionsForClient: [
      "What's the right default lead-window — how many days before a budget window or renewal date should the first follow-up draft appear?",
      "For each salesperson, can you provide a few sample emails so we can build a voice profile that sounds like them rather than generic?",
    ],
    edgeCases: [
      "Duplicate triggers for the same contact collapse into one entry",
      "Client already replied before the window opened — stand down, no draft",
      "Missing rate/opportunity data — draft goes out without a price and is flagged",
      "Reply-match false positive from a shared inbox — requires a thread-ID match, not just sender",
      "Salesperson reassignment — resolves the current record owner at queue time, not at trigger creation",
    ],
    dependsOn: ["sales-008", "sales-010", "sales-013"],
  },
  {
    id: "sales-013",
    code: "SALES-013",
    name: "Morning Follow-Up Queue with Drafts",
    stage: "stage3",
    effort: "Medium · Est. 4–6 days",
    whatItDoes:
      "Every working morning, presents each salesperson a single value/urgency-ranked queue of due follow-ups, each one carrying a pre-drafted email ready to review, tweak, and send — the central guardrail: the system never auto-sends, a human always does.",
    howItWorks: [
      "Runs once per working morning per user's timezone, plus an on-demand refresh option",
      "Pulls every due entry for that owner: fired triggers, awaited replies past their SLA, and call-backs due today",
      "Enriches each with its opportunity value and ranks the list by a weighted combination of value and urgency",
      "Any entry missing a draft (not already produced upstream) gets one generated on the spot",
      "Renders the ranked queue in a per-salesperson view and notifies them it's ready",
      "Send/Defer/Skip actions each log back to Act! — Send creates the email from the rep's own mailbox and logs history, Defer reschedules to the next working day, Skip logs a dropped reason",
    ],
    systemsAndData: [
      "Review-queue store (backing the review UI)",
      "Act! Web API (Opportunities, History, Activities)",
      "LLM API (only for entries missing a draft)",
      "Email send via draft-into-mailbox",
      "Team notification channel",
    ],
    requirements: [
      "Draft-into-mailbox permission for every rep's mailbox",
      "Value/urgency weighting agreed with sales leadership for the ranking formula",
    ],
    questionsForClient: [
      "What time each morning should the queue be delivered, and does this need to respect each rep's own working-day calendar/timezone?",
      "How should we weight ranking between opportunity value and urgency — is value the dominant factor, or should urgency (e.g. an overdue reply) usually win?",
    ],
    edgeCases: [
      "Empty queue still sends a \"nothing due\" note rather than silence",
      "Draft generation failing for one entry never blocks the whole queue — shown with a retry option",
      "A send failure (mailbox auth issue) keeps the entry pending and surfaces the error rather than falsely logging it as sent",
      "The same contact appearing in two entries is merged or ordered adjacently",
      "A deferred item re-surfaces the next working day, not the same day",
    ],
    dependsOn: ["sales-012", "sales-005", "sales-020", "sales-021", "sales-022", "sales-023"],
  },
  {
    id: "sales-005",
    code: "SALES-005",
    name: "Personal Touchpoint Reminders",
    stage: "stage3",
    effort: "Low · Est. 2–3 days",
    whatItDoes:
      "On the day a recorded personal date falls due — return from leave, an anniversary, a promised catch-up — drafts a short, warm personal note in the salesperson's own voice into their morning queue, and never nags twice about the same one.",
    howItWorks: [
      "Runs daily, early morning, selecting touchpoints tagged (by SALES-008/010) whose date matches today",
      "For each, fetches the contact, the occasion detail, and recent activity for context on \"what's happened since\"",
      "Checks a skip/handled ledger so the same prompt never re-appears once dismissed",
      "The LLM drafts a short, occasion-appropriate note matched to the rep's voice",
      "The draft lands in the owner's morning queue (SALES-013) rather than sending automatically",
    ],
    systemsAndData: [
      "Act! Web API (Contacts filtered by touchpoint date field, Notes, History)",
      "SQL read fallback for date-field filtering",
      "LLM API",
      "SALES-013 queue",
    ],
    requirements: [
      "A consistent Act! field or note tag for personal touchpoint dates, fed by SALES-008/010",
    ],
    questionsForClient: [
      "Are there occasion types that should never be automated — e.g. a bereavement — and should always route to a manual-only reminder instead of an AI-drafted note?",
    ],
    edgeCases: [
      "Vague or missing occasion detail — falls back to a generic-but-warm note, flagged low confidence",
      "Sensitive occasions (e.g. bereavement) route for manual handling only",
      "Recurring annual touchpoints only fire on the correct date, not every day",
      "Contact has left the company — suppressed",
      "Once skipped, an item never reappears the next day",
    ],
    dependsOn: ["sales-008", "sales-010", "sales-013"],
  },
  {
    id: "sales-020",
    code: "SALES-020",
    name: "Tailored Proposal Assembly",
    stage: "stage3",
    effort: "Medium · Est. 4–6 days",
    whatItDoes:
      "On request, assembles an on-brand, voice-matched proposal draft pulling from Act! history, the Sales Order Register, and the editorial plan — ready for a salesperson to tweak and send, with prices always sourced from real data, never invented.",
    howItWorks: [
      "Triggered on-demand by a salesperson requesting a proposal for a specific contact/title",
      "Fetches Act! context: client history, rates, and the last conversation",
      "Looks up that client's previous bookings in the Sales Order Register",
      "Pulls the relevant feature/product and current price from the editorial plan and rate card",
      "The LLM drafts the proposal narrative in the rep's voice, arranging and justifying line items that come from real data rather than inventing prices",
      "The draft is merged into a branded house template and delivered to the rep's queue; on send, it's logged to Act! History with a follow-up trigger created for SALES-012",
    ],
    systemsAndData: [
      "Act! Web API (contact/opportunity/history reads)",
      "SOR reader (format to confirm)",
      "Editorial plan source",
      "LLM API",
      "House-format template engine (docx/HTML)",
    ],
    requirements: [
      "SOR access in whatever format it exists (Excel file location, or DB connection)",
      "A source for the current editorial plan/feature list",
      "A current rate card in a structured, referenceable form",
      "A house proposal template (branded document format)",
    ],
    questionsForClient: [
      "Can you share the current SOR file/location and confirm who has write access to it, so we can build a reliable read connector?",
      "Is there an existing branded proposal template (Word/HTML) we should build from, or does one need to be designed?",
      "Where does the current/upcoming editorial plan live, and how often does it change?",
    ],
    edgeCases: [
      "SOR access or format changes must fail loudly, never silently drop history",
      "New client with no previous bookings — assembles from the catalogue only, flagged as such",
      "Rate-card ambiguity presents options rather than guessing",
      "Editorial feature not found is omitted and flagged, not fabricated",
      "Currency/VAT/discount decisions are left to rep judgement, not automated",
    ],
    dependsOn: ["sales-013"],
  },
  {
    id: "sales-021",
    code: "SALES-021",
    name: "Renewal Outreach with Previous Placements",
    stage: "stage3",
    effort: "Medium · Est. 4–6 days",
    whatItDoes:
      "When a guide or issue opens its next cycle, drafts a personal renewal email to every previous advertiser — linking their actual prior ad and quoting this year's price — while automatically excluding anyone already booked for the new cycle.",
    howItWorks: [
      "Triggered when a cycle opens for a given title/edition",
      "Pulls the previous edition's advertiser list from the SOR and subtracts anyone already booked for the new cycle, including annual-series clients who should never be re-approached this way",
      "For each remaining advertiser, resolves the Act! contact and owning rep, locates their previous placement's page URL, and looks up this year's equivalent price",
      "The LLM drafts a \"we're running this again\" email in the owner's voice, referencing the actual prior ad and stating the current price",
      "Drafts are delivered to the owning reps' queues; once the pass completes, the remaining un-approached advertisers are handed to the campaign engine, excluding anyone directly approached here",
    ],
    systemsAndData: [
      "SOR reader",
      "Digital-edition platform (deep-link lookup)",
      "Rate card source",
      "Act! Web API (Contacts, owner lookup, History)",
      "LLM API",
      "Campaign engine handoff",
    ],
    requirements: [
      "SOR access with prior-edition advertiser data and current-cycle booking status",
      "Confirmation the digital-edition platform can produce a stable, durable per-advertiser page URL",
      "A defined list/rule for annual-series clients who should be excluded from this flow",
    ],
    questionsForClient: [
      "Does your digital-edition platform expose a permanent URL for a specific advertiser's placement in a specific past issue, or would we need to construct one from a pattern? Can you share an example?",
      "Which clients are on annual-series deals that should never receive this kind of renewal-pass email?",
      "What campaign tool, if any, currently handles the wider (non-directly-approached) advertiser outreach, so we can hand off correctly?",
    ],
    edgeCases: [
      "Advertiser already booked but the SOR is lagging — SOR booking status is treated as source of truth and re-checked at send time",
      "No stable per-advertiser URL available — falls back to an issue-level link, flagged",
      "Annual-series client wrongly included — needs an explicit exclusion list",
      "Price not yet set for the new cycle — draft is held",
      "Contact owner unknown — falls back to a designated owner queue",
    ],
    dependsOn: ["sales-013"],
  },
  {
    id: "sales-022",
    code: "SALES-022",
    name: "Sales Template Library & Save-the-Sale Responses",
    stage: "stage3",
    effort: "Low · Est. 2–3 days",
    whatItDoes:
      "Turns salespeople's private Word template libraries into one shared engine that automatically selects and personalises the right template — including a save-the-sale reply to a \"no\" — delivered as a voice-matched draft.",
    howItWorks: [
      "Fires when a sales situation calls for a standard email: new-prospect outreach, existing-advertiser contact, join-the-project invite, or an inbound decline",
      "For inbound situations, classifies which template family applies, using deterministic rules first and an LLM fallback for anything unclear",
      "Fetches the recipient's context from Act! and personalises the chosen template in the rep's voice",
      "For a decline specifically, follows an acknowledge-probe-offer pattern: acknowledge the no, ask the reason, and offer a lower-cost alternative from a defined catalogue where one exists",
      "The draft is delivered to the queue; on send, it's logged to Act! History",
    ],
    systemsAndData: [
      "Template store (keyed by family + tags)",
      "Act! Web API (contact/history reads, History write)",
      "LLM API (family selection + personalisation)",
    ],
    requirements: [
      "Access to every salesperson's existing private Word template library for one-off migration into the shared store",
      "A defined \"save-the-sale\" alternative catalogue (e.g. lower-cost package options) to offer on a decline",
    ],
    questionsForClient: [
      "Can each salesperson share their current template documents so we can migrate them into one shared, curated library?",
      "What lower-cost alternatives or fallback offers should be available when a prospect declines on budget grounds?",
    ],
    edgeCases: [
      "Misclassified template family — deterministic rules override where the signal is clear, low-confidence routes to manual pick",
      "A decline with no viable alternative still gets an acknowledge/ask response without a forced offer",
      "Template drift over time — handled with per-user overrides on top of a shared base",
      "Missing personalisation fields are flagged as placeholders, never sent raw",
    ],
    dependsOn: ["sales-013"],
  },
  {
    id: "sales-023",
    code: "SALES-023",
    name: "Meeting Notes → Pitch Conversion",
    stage: "stage3",
    effort: "Medium · Est. 3–5 days",
    whatItDoes:
      "Converts captured meeting notes into a client-specific pitch draft, drawing on the strongest elements of similar prior pitches, in the owner's own voice and the house layout — turning a scattered set of notes into a ready-to-tailor pitch document.",
    howItWorks: [
      "Triggered by a meeting flagged as pitch-worthy, either from the transcription pipeline or a manual \"make a pitch from this\" action with notes attached",
      "An extraction pass pulls out the client's situation, positioning angle, budget signals, and what they responded well to",
      "The brief is embedded and used to retrieve the closest matching previous pitches from a pitch store",
      "A drafting pass synthesises a new pitch that answers what the client actually said, lifting the strongest structural elements (not stale figures) from retrieved pitches",
      "The draft is merged into the house layout and delivered to the owner's queue; on send, the new pitch is indexed back into the pitch store for future retrieval",
    ],
    systemsAndData: [
      "Teams/Zoom transcription",
      "Vector store (pitch retrieval)",
      "LLM API (extraction + drafting)",
      "Act! Web API (Contacts, History)",
      "House-template engine",
    ],
    requirements: [
      "A seed set of existing won pitches to embed into the pitch store before this is useful",
      "A house pitch layout/template",
    ],
    questionsForClient: [
      "Can you provide a batch of your best existing pitch decks/documents to seed the pitch library, ideally tagged with which ones won and why?",
      "Is there a house layout or brand template these pitches need to follow?",
    ],
    edgeCases: [
      "Thin or low-quality notes — flagged low confidence, more detail requested before drafting",
      "No similar prior pitch exists (cold start) — drafts from the brief alone, marked as no-retrieval",
      "A retrieved pitch has stale pricing/product info — only its structure/angle is reused, never its figures",
      "Sensitive or off-record remarks in notes are excluded from the client-facing draft",
      "Wrong contact attribution is confirmed before logging",
    ],
    dependsOn: ["sales-013"],
  },

  // ---------- STAGE 4 ----------
  {
    id: "sales-024",
    code: "SALES-024",
    name: "Per-Project Prospect Pipeline",
    stage: "stage4",
    effort: "Medium · Est. 4–6 days",
    whatItDoes:
      "Gives every salesperson a live, shared pipeline organised by project and magazine issue that automatically captures prospects as they're approached and captures billing details the moment a deal closes.",
    howItWorks: [
      "Classifies outbound emails to see if they represent a genuine tracked approach, resolving the recipient to an Act! contact by email/domain",
      "A matched approach upserts a pipeline row keyed by project, issue, and contact with status \"contacted\"; a manual-entry option in the review UI covers conversations that didn't happen by email",
      "Status transitions follow an enforced state machine (to_contact → contacted → replied → interested → booked/declined)",
      "On booked/close, a billing-capture form appears; submitting it writes an Act! Opportunity and pushes a structured close record into the Sales Order Register",
      "A one-off migration step parses each salesperson's existing personal spreadsheet/notebook into normalised pipeline rows",
    ],
    systemsAndData: [
      "Outbound email stream (platform to confirm)",
      "Act! Web API (Contacts, Opportunities)",
      "Pipeline store (Postgres)",
      "Human-review UI",
      "SOR (for the close hand-off)",
    ],
    requirements: [
      "Access to each salesperson's existing personal spreadsheet/notebook for one-off migration",
      "SOR write access (or an agreed close-record format) for the booking hand-off",
      "An agreed project/issue taxonomy",
    ],
    questionsForClient: [
      "Can each salesperson export their current tracking spreadsheet/notebook so we can migrate existing pipeline data rather than starting from zero?",
      "What fields do you need captured at the point of booking — billing contact, address, PO number, booking spec, value, currency — is this list complete or is anything missing?",
      "What's the current project/issue naming convention, so the pipeline structure matches how your team already thinks about it?",
    ],
    edgeCases: [
      "Email matches multiple Act! contacts — routed to review",
      "Prospect not yet in Act! — a stub is created or held in review",
      "Duplicate approaches to the same contact+issue are deduped on a key",
      "Migration rows with ambiguous project/issue go to a review queue",
      "Status regressions are blocked by the state machine",
      "SOR unavailable at close time — the record is queued and retried",
    ],
    dependsOn: [],
  },
  {
    id: "sales-025",
    code: "SALES-025",
    name: "Pipeline Status Updates & Chase Lists",
    stage: "stage4",
    effort: "Medium · Est. 3–5 days",
    whatItDoes:
      "Keeps pipeline statuses current automatically from replies, bounces, and booking confirmations, and surfaces gone-quiet prospects as a chase list with a drafted nudge — nothing sends automatically.",
    howItWorks: [
      "Inbound email is resolved to a tracked prospect by sender/thread ID",
      "The message intent is classified: reply-interested, reply-decline, bounce, booking-confirmation, or neutral",
      "The pipeline status transitions accordingly and the change is logged to both the pipeline store and Act! History",
      "A decline routes to a save-the-sale draft where eligible, or schedules a later touchpoint otherwise",
      "A daily scheduled sweep finds prospects untouched past their interval and builds a chase list with a drafted nudge per entry for review",
    ],
    systemsAndData: [
      "Email read connector",
      "Pipeline store (from SALES-024)",
      "Act! History",
      "LLM API (classification + nudge drafting)",
      "Human-review queue",
    ],
    requirements: [
      "Inbound email read access across tracked prospect threads",
    ],
    questionsForClient: [
      "What chase interval feels right per pipeline stage — e.g. how many days of silence before a \"contacted\" prospect should appear on the chase list?",
      "Under what conditions should a decline trigger a save-the-sale offer versus just being logged and scheduled for a later touchpoint?",
    ],
    edgeCases: [
      "Ambiguous reply — goes to review, no automatic status transition",
      "Booking confirmation with no matching prospect — goes to review/create",
      "Soft-fail vs hard-fail bounces are treated differently",
      "Out-of-office replies are suppressed from being misread as a real reply",
      "Duplicate booking confirmations are idempotent on the booking reference",
    ],
    dependsOn: ["sales-024"],
  },
  {
    id: "sales-026",
    code: "SALES-026",
    name: "Sales Activity Dashboard",
    stage: "stage4",
    effort: "Medium · Est. 5–7 days",
    whatItDoes:
      "A live dashboard of booked/forecast revenue and per-person sales activity, built entirely from the automation by-products of the other workflows, with cycle-on-cycle comparison and drill-down to source records — mostly aggregation, minimal AI, deterministic numbers.",
    howItWorks: [
      "An activity collector reads the append-only event log from SALES-024/025 (proposals sent, follow-ups, replies, bookings) and buckets it by salesperson × title × product × period",
      "A revenue collector pulls SOR bookings and Xero invoiced/actual figures, reconciling the two on invoice/booking reference to avoid double-counting",
      "An aggregation job computes each metric into a metrics store keyed by dimension and period",
      "A comparison job measures each metric against the equivalent point in the prior cycle, aligned by issue date rather than calendar date",
      "Every dashboard tile links back to its underlying source records for drill-down",
    ],
    systemsAndData: [
      "SOR reader",
      "Xero Accounting API (read)",
      "Pipeline/activity store (from SALES-024/025)",
      "Metrics store",
      "Dashboard surface (built into this app)",
    ],
    requirements: [
      "SOR read access in whatever current format",
      "Xero API access scoped to the correct organisation/tenant, read-only",
      "Agreed metric definitions with sales leadership",
    ],
    questionsForClient: [
      "Which Xero organisation/tenant should this connect to, and can you provision read-only API access?",
      "What does \"the equivalent point in the prior cycle\" mean for your titles — are cycles aligned to calendar months, or to each issue's own publication schedule (which can shift)?",
      "Explicitly confirmed in the original spec: no approval gate or policing on this dashboard — is that still the right cultural fit, i.e. purely informational, no forms to fill in?",
    ],
    edgeCases: [
      "SOR schema drift or manual Excel edits breaking the parser — needs a schema-guard and alert",
      "Xero token expiry — refresh with fail-soft behaviour",
      "A booking appearing in both SOR and Xero must be deduped on reference, not double-counted",
      "Cycle alignment when issue dates shift needs issue-relative comparison logic, not calendar-relative",
      "Missing dimension tags are surfaced as an \"unattributed\" bucket rather than silently dropped",
    ],
    dependsOn: ["sales-024", "sales-025", "sales-027"],
  },
  {
    id: "sales-027",
    code: "SALES-027",
    name: "Sold-Work Delivery Tracking",
    stage: "stage4",
    effort: "Medium · Est. 3–5 days",
    whatItDoes:
      "Tracks every sold item through the production, editorial, and events hand-offs, flagging anything that stalls beyond its expected window with an owner and an age — mostly rules-based, catching things that go quiet even without an explicit signal.",
    howItWorks: [
      "When a booking is confirmed, a delivery item is created with its type, promised spec, owning team, current stage, and expected-completion window",
      "As the item moves between teams, its stage and owner are updated — from structured signals (status emails, Act! Activity completion) or a manual update where no automatic signal exists",
      "A daily stall-detection sweep compares how long an item has been in its current stage against the expected window for that stage/type, flagging it stalled with the owner and age if exceeded",
      "Stalls are pushed to the owning team and the selling rep",
      "Completion and stall counts roll up into the revenue dashboard and the weekly leadership summary",
    ],
    systemsAndData: [
      "Delivery-tracking store",
      "Act! Activities/History",
      "Email/Teams for hand-off signals",
      "Human-review UI (sold-work view)",
      "SOR read for booking detail",
    ],
    requirements: [
      "Agreed expected-completion windows per item type and stage from production/editorial/events teams",
      "A way to capture hand-off signals from three different teams that may not share consistent tooling today",
    ],
    questionsForClient: [
      "For each type of sold item (advertorial, banner, event package), what's a realistic expected time in each production stage before it should be flagged as stalled?",
      "How do production, editorial, and events currently signal that something has moved to the next stage — is there any existing structured system, or is this entirely informal today (email, verbal, spreadsheets)?",
    ],
    edgeCases: [
      "A team that never sends a hand-off signal — the sweep still flags on age alone",
      "An item can skip a stage (non-linear transitions allowed)",
      "Ambiguous hand-off emails route to review",
      "Cancelled/refunded bookings are closed out and excluded from stall counts",
      "A type with no expected window configured falls back to a default plus a config alert",
    ],
    dependsOn: ["sales-024", "sales-025", "sales-026"],
  },
  {
    id: "sales-028",
    code: "SALES-028",
    name: "Weekly Management Summary & Alerts",
    stage: "stage4",
    effort: "Low · Est. 2–3 days",
    whatItDoes:
      "Delivers a short, written weekly leadership brief drawn straight from the dashboard data, and fires early alerts whenever an open issue or event is tracking materially behind its equivalent point in the prior cycle — read-only, informational, no approval gate.",
    howItWorks: [
      "On a weekly schedule, pulls the essentials from the metrics store: revenue position by title/issue, activity highlights, stalled items, and exceptions needing a decision",
      "The LLM composes a short, readable narrative brief from these structured inputs, with an evidence link per point — figures always come from the metrics store, never invented by the model",
      "The brief is delivered to leadership and archived for cross-cycle trend review",
      "A continuous comparison sweep separately checks each open issue/event against its prior-cycle equivalent point; if the gap exceeds a threshold, an alert fires immediately with the gap quantified and linked records",
    ],
    systemsAndData: [
      "Metrics store (from SALES-026/027, read-only)",
      "LLM API (brief drafting)",
      "Email/Teams delivery",
      "Summary archive store",
    ],
    requirements: [
      "A confirmed leadership recipient list",
      "Agreed alert-gap thresholds per title/event type",
    ],
    questionsForClient: [
      "Who should receive the weekly brief and the real-time behind-schedule alerts — is this the same group, or different audiences?",
      "What day and time should the weekly brief go out?",
      "How far behind the prior cycle's equivalent point should an issue/event be before it's worth an urgent alert, versus just showing up in the next weekly brief?",
    ],
    edgeCases: [
      "Sparse data early in a cycle suppresses false \"behind schedule\" alerts until a comparable point is reached",
      "Cycle misalignment (issue dates shifting) is handled with issue-relative, not calendar, comparison",
      "Duplicate alerts for the same subject are deduped with a cooldown window",
      "If the model omits a section, a template guarantees all sections still render with raw figures as fallback",
      "Delivery failure triggers a retry and an admin flag",
    ],
    dependsOn: ["sales-026", "sales-027"],
  },
];
